// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {feed} from '../models';

export function AddUser(arg1:string):Promise<main.Settings>;

export function CancelDeviceLogin():Promise<void>;

export function CompleteDeviceLogin(arg1:string,arg2:number,arg3:number):Promise<string>;

export function FetchFeed():Promise<feed.Result>;

export function FetchUserFeed(arg1:string):Promise<feed.Result>;

export function GetSettings():Promise<main.Settings>;

export function RemoveUser(arg1:string):Promise<main.Settings>;

export function StartDeviceLogin():Promise<main.DeviceLogin>;
