// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {feed} from '../models';

export function AddUser(arg1:string):Promise<main.Settings>;

export function FetchFeed():Promise<feed.Result>;

export function FetchUserFeed(arg1:string):Promise<feed.Result>;

export function GetSettings():Promise<main.Settings>;

export function RemoveUser(arg1:string):Promise<main.Settings>;

export function SetToken(arg1:string):Promise<string>;
