// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddUser(arg1) {
  return window['go']['main']['App']['AddUser'](arg1);
}

export function AddUsers(arg1) {
  return window['go']['main']['App']['AddUsers'](arg1);
}

export function CancelDeviceLogin() {
  return window['go']['main']['App']['CancelDeviceLogin']();
}

export function CompleteDeviceLogin(arg1, arg2, arg3) {
  return window['go']['main']['App']['CompleteDeviceLogin'](arg1, arg2, arg3);
}

export function FetchFeed() {
  return window['go']['main']['App']['FetchFeed']();
}

export function FetchGitHubFollowing() {
  return window['go']['main']['App']['FetchGitHubFollowing']();
}

export function FetchTrending(arg1, arg2) {
  return window['go']['main']['App']['FetchTrending'](arg1, arg2);
}

export function FetchUserFeed(arg1) {
  return window['go']['main']['App']['FetchUserFeed'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function MarkReactionsRead() {
  return window['go']['main']['App']['MarkReactionsRead']();
}

export function PollReactions() {
  return window['go']['main']['App']['PollReactions']();
}

export function RemoveUser(arg1) {
  return window['go']['main']['App']['RemoveUser'](arg1);
}

export function SignOut() {
  return window['go']['main']['App']['SignOut']();
}

export function StartDeviceLogin() {
  return window['go']['main']['App']['StartDeviceLogin']();
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
