// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddUser(arg1) {
  return window['go']['main']['App']['AddUser'](arg1);
}

export function FetchFeed() {
  return window['go']['main']['App']['FetchFeed']();
}

export function FetchTrending(arg1, arg2) {
  return window['go']['main']['App']['FetchTrending'](arg1, arg2);
}

export function FetchUserFeed(arg1) {
  return window['go']['main']['App']['FetchUserFeed'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function RemoveUser(arg1) {
  return window['go']['main']['App']['RemoveUser'](arg1);
}

export function SetToken(arg1) {
  return window['go']['main']['App']['SetToken'](arg1);
}
